#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

staged_files=$(git diff --cached --name-only | grep -Ev 'package-lock\.log|yarn\.log')

npx prettier ${staged_files} --check
npx eslint ${staged_files}
